# Copyright (c) 2024 Semtech Corporation
# SPDX-License-Identifier: Apache-2.0

# ------------------------------ General configuration ------------------------------

CONFIG_USE_SEGGER_RTT=n

# stack size (Zephyr boilerplate + 2048 required by Semtech)
CONFIG_MAIN_STACK_SIZE=4096

# some operations will be triggered from the system workq, so match above stack size
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

CONFIG_LOG=y

CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_PM_DEVICE=y

CONFIG_WATCHDOG=y

CONFIG_FLASH=y

# ------------------------------ Transceiver driver ----------------------------

CONFIG_LORA_BASICS_MODEM_DRIVERS=y
CONFIG_LORA_BASICS_MODEM_DRIVERS_EVENT_TRIGGER_GLOBAL_THREAD=y

# ------------------------------ LoRa Basics Modem -----------------------------

CONFIG_LORA_BASICS_MODEM=y
CONFIG_LORA_BASICS_MODEM_MAIN_THREAD=n

CONFIG_LORA_BASICS_MODEM_LOG_LEVEL_DBG=y
CONFIG_LORA_BASICS_MODEM_LOG_VERBOSE=y

CONFIG_LORA_BASICS_MODEM_GEOLOCATION=y
CONFIG_LORA_BASICS_MODEM_ALMANAC=y
CONFIG_LORA_BASICS_MODEM_STORE_AND_FORWARD=y

CONFIG_LORA_BASICS_MODEM_CRYPTOGRAPHY_SOFT=n
